# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd3e7dacddd71469486048c2cfdf629253e40ab984578267718aa8e12b734c774b1cbce9c653f5e371e63a3b6a9e224f34563f575e87ff7987a24d126ad9b7a3

test:
  secret_key_base: ba32dad1a2563d1dffec7469bd76ed0a710a7f8243c4b48c427a543172d7aab9780620fdd545aecfc193df17d961237eeb141bbcc3b56f7db4a1205cf1f0e24e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
